---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 02/04/2023 19:23
---

CreateThread(function()
    while (not SM:hasPlayerSpawned()) do
        Wait(0)
    end

    while (not NetworkIsPlayerActive(PlayerId())) do
        Wait(0)
    end

    SM:onClientLoaded()
end)