---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 05/05/2023 11:21
---


CreateThread(function()
    SM:spawnPlayer({
        x = -1039.27,
        y = -2736.09,
        z = 13.77 - 1.0,
        heading = 324.09,
        model = 'a_m_y_skater_01',
        fadeOut = true,
        fadeIn = false,
        isVisible = false,
    })
end)

function SM:onClientLoaded()
    DoScreenFadeIn(1000)
    SetEntityVisible(PlayerPedId(), true)
end