---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 05/09/2024 17:39
---

RegisterCommand("revive", function()
    if (IsEntityDead(PlayerPedId())) then
        local coords <const> = GetEntityCoords(PlayerPedId())

        NetworkResurrectLocalPlayer(coords.x, coords.y, coords.z, GetEntityHeading(PlayerPedId()), false, false)
        SetPlayerInvincible(PlayerPedId(), false)
        ClearPedBloodDamage(PlayerPedId())
    end
end)