---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 05/09/2024 17:36
---

RegisterCommand("tpm", function()
    local waypointHandle = GetFirstBlipInfoId(8)
    if DoesBlipExist(waypointHandle) then
        CreateThread(function()
            local waypointCoords = GetBlipInfoIdCoord(waypointHandle)
            local foundGround, zCoords, zPos = false, -500.0, 0.0

            while (not foundGround) do
                zCoords = zCoords + 10.0
                RequestCollisionAtCoord(waypointCoords.x, waypointCoords.y, zCoords)
                Wait(0)
                foundGround, zPos = GetGroundZFor_3dCoord(waypointCoords.x, waypointCoords.y, zCoords)

                if (not foundGround and zCoords >= 2000.0) then
                    foundGround = true
                end
            end

            SetPedCoordsKeepVehicle(PlayerPedId(), waypointCoords.x, waypointCoords.y, zPos)
        end)
    else
        print("no waypoint")
    end
end)