---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 05/09/2024 17:30
---

RegisterCommand("car", function(_, args)
    local model = args[1] or "t20"

    if (not IsModelInCdimage(model)) or (not IsModelAVehicle(model)) then
        return
    end

    RequestModel(model)
    while (not HasModelLoaded(model)) do
        Wait(1)
    end

    local veh = CreateVehicle(GetHashKey(model), GetEntityCoords(PlayerPedId()), GetEntityHeading(PlayerPedId()), true, false)
    SetPedIntoVehicle(PlayerPedId(), veh, -1)
end)

RegisterCommand("dv", function(_, args)
    local veh = GetVehiclePedIsIn(PlayerPedId(), false)
    if (veh ~= 0) then
        DeleteEntity(veh)
    else
        local pos = GetEntityCoords(PlayerPedId())
        local vehicles = GetGamePool("CVehicle")
        local radius = tonumber(args[1]) or 5.0
        for i = 1, #vehicles do
            local vehToDelete = vehicles[i]
            if (vehToDelete ~= 0) then
                local vehPos = GetEntityCoords(vehToDelete)
                if #(pos - vehPos) < radius then
                    DeleteEntity(vehToDelete)
                end
            end
        end
    end
end)