---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 04/05/2023 14:09
---

fx_version "adamant"

game "gta5"

client_script "client/empty.lua"
server_script "server/host_lock.lua"