---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 02/09/2024 11:04
---

version "0.0.1"
author "KraKss"

fx_version "cerulean"

game "gta5"

lua54 "yes"

resource_type "gametype" { name = "Template" }

--managers
client_scripts {
    "managers/mapmanager/mapmanager_shared.lua",
    "managers/mapmanager/mapmanager_client.lua",
    "managers/hardcap/client.lua",

    "managers/spawnmanager/define.lua",
    "managers/spawnmanager/gamemodeLoader.lua",
    "managers/spawnmanager/spawn.lua",
    "managers/spawnmanager/spawnmanager.lua",
}

server_scripts {
    "managers/mapmanager/mapmanager_shared.lua",
    "managers/mapmanager/mapmanager_server.lua",
    "managers/hardcap/server.lua",
}

shared_scripts {
}

client_scripts {
}

server_scripts {
    "src/vendors/oxmysql/dist/build.js",
	"src/vendors/oxmysql/lib/MySQL.lua",
}